---
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'debian/**'
      - 'subprojects/**'
    branches:
      - master
  pull_request:
    paths-ignore:
      - 'debian/**'
      - 'subprojects/**'
    branches:
      - master

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - id: checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            meson \
            ccache \
            nlohmann-json3-dev \
            zlib1g-dev \
            libcurl4-openssl-dev \
            libfmt-dev \
            libyaml-cpp-dev \
            libpcre2-dev \
            libsystemd-dev

      - id: cache-ccache
        uses: hendrikmuhs/ccache-action@v1

      - name: Configure
        run: |
          meson setup \
            -Dwrap_mode=nofallback \
            output

      - name: Build
        run: ninja -C output -v
